version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: activesupport
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: activejob
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: actionview
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: railties
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: actionpack
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: activerecord
    versions:
    - 5.2.4.5
  - dependency-name: loofah
    versions:
    - 2.9.0
